apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-pv
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /opt/nfs
    server: path.to.master.server
    readOnly: false
