apiVersion: v1
kind: PersistentVolume
metadata:
  name: ci
  labels: 
    volume: ci
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /var/nfsshare
    server: master.giraf.cs.aau.dk
    readOnly: false
