apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-pv 
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteMany    
  glusterfs:         
    endpoints: gluster-cluster 
    path: /Artifactory 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
