apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv   
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteMany    
  glusterfs:         
    endpoints: gluster-cluster 
    path: /Jenkins
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
