---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-pod
  labels:
    name: jenkins-pod  
spec:
  containers:
  - name: jenkins-pod
    image: jenkins
    ports:
    - name: http
      containerPort: 8080
    securityContext:
      privileged: true
    volumeMounts:
    - name: jenkins-vol
      mountPath: /var/jenkins_home 
      readOnly: false
  securityContext:
    supplementalGroups: [590]       
  volumes:
  - name: jenkins-vol 
    persistentVolumeClaim:
      claimName: jenkins-claim
