---
kind: Endpoints
apiVersion: v1
metadata:
  name: gluster-cluster
subsets:
- addresses:
  - ip: 10.0.0.10
  ports:
  - port: 1
- addresses:
  - ip: 10.0.0.11
  ports:
  - port: 1
  addresses:
  - ip: 10.0.0.12
  ports:
  - port: 1
  addresses:
  - ip: 10.0.0.13
  ports:
  - port: 1
