apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv   
spec:
  capacity:
    storage: 15Gi
  accessModes:
  - ReadWriteMany    
  glusterfs:         
    endpoints: gluster-cluster 
    path: /GlusterVol 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
